### ISSUE TITLE
how to install the "map"

### ISSUE THREAD

**Issue by InLaw** [conda-incubator/conda-suggest#6]
"assumes that the map files for the conda-forge channel have also been installed"

-> What ways exist to install the "map" for the files?

**Comment by scopatz** [comment]
[`conda-suggest-conda-forge`](https://github.com/regro/conda-suggest-conda-forge) is one such collection of map files, you can install it with `conda install -c conda-forge conda-suggest-conda-forge`

**Comment by InLaw** [comment]
thanks
is it possible to get it without to install conda?
- as a file

**Comment by scopatz** [comment]
Yes you just need to copy a file to the $CONDA_SUGGEST_PATH, as per the readme: https://github.com/conda-incubator/conda-suggest#map-files

**Comment by InLaw** [comment]
where can I get the file from?

**Comment by scopatz** [comment]
You can get the file by generating it or from that other repo: https://github.com/regro/conda-suggest-conda-forge

**Comment by InLaw** [comment]
thanks for your help and fast response
